name: Docker CI Cloud Tools

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile*'
      - '**/package.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}

      - name: Get package name and version
        id: package
        run: |
          echo "PACKAGE_NAME=$(jq -r '.name' package.json)" >> $GITHUB_ENV
          echo "PACKAGE_AUTHOR=$(jq -r '.author' package.json)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Setup Repo
        run: |
          echo "REPO=${{env.PACKAGE_AUTHOR}}/${{env.PACKAGE_NAME}}" >> $GITHUB_ENV
          
      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t $REPO:$SHA -t $REPO:latest -t $REPO:$PACKAGE_VERSION .

      - name: Push Docker image
        run: |
          docker push $REPO:$SHA
          docker push $REPO:$PACKAGE_VERSION
          docker push $REPO:latest